### ISSUE TITLE
Asset page changes

### ISSUE THREAD

**Issue by oxarbitrage** [oxarbitrage/bitshares-explorer#11]
After working on the assets page with @tbone-bts at https://github.com/oxarbitrage/bitshares-explorer/issues/2 i made osme changes to the individual asset page like: http://bitshares-explorer.io/#/assets/1.3.113

Any change or addition please let me know but please keep in mind that every change, for simple it may seems can take lot of time so please only send what you think is really needed. 

The plan is to add table sorting to every section of the explorer, in every table possible and fine tune every section. This process will be repeated in the future to fix/add whatever left behind.

**Comment by oxarbitrage** [comment]
no feedback, closing with the changes i made, sample: http://bitshares-explorer.io/#/assets/1.3.1152

**Comment by tbone-bts** [comment]
The assets page has had tremendous progress.  Thanks for that!  There are still a few items and I've been meaning to leave more feedback, just been so busy.  Can it be reopened, or does a new one need to be started?  Here are some notes:

1. I think the chart value is off by an order of magnitude.  
2. the distinction between gateway UIAs vs. native UIAs you added is very helpful.  can you also reflect that in the Type column?  i.e. User Issued (Native) vs. User Issued (Gateway)? 
3. this page has become very useful.  that usefulness could really be expanded by giving user ability to switch from BTS as base currency to fiat of their choice.  to me personally USD is most useful
4. can you make any reference to 24 hour "24h" instead of "24 hs"? in the U.S. we commonly use "24hr", and looks like you guys use "24 hs"....but I think "24h" is more universal and cleaner.   
5. The values in the upper left need some work.  i made some notes several days ago that i didn't get to finish and now i can't find them.  but to start, the market cap values shouldn't say 24h, only the volumes.  also, BTS market cap doesn't make sense in BTS terms.  market cap should be in terms of BTC, USD, and CNY.   although one other thing i'm noticing, i'm not even sure those "market cap" numbers are really the market cap (i.e. total value of outstanding BTS tokens).  is that what you intended it to be?
6. i see the line around the column that is sorted is too much trouble.  changing the background might be easier.  although honestly, that is not really necessary. other items are much more important.  plus now that you have an arrow only on the sorted column, it's obvious enough which column is sorted.  i would just remove the line since it's not really working as intended.

**Comment by oxarbitrage** [comment]
please move this comments to the assetS issue (https://github.com/oxarbitrage/bitshares-explorer/issues/2) or open new one. This is the issue for the individual asset page. closing again.

just for your consideration from the points posted here some of them will not be done at least by now.

1- pls explain more, i am not understanding the "off by 1 magnitude thing"
3- will not be done now, too hard.
6- whatever you mean there will not be done. 

working on the rest of them now.
