### ISSUE TITLE
HTTP 500 when querying some assets

### ISSUE THREAD

**Issue by HarukaMa** [oxarbitrage/bitshares-explorer#15]
I've been creating new assets after the fee change, but when I check them in the explorer I can't see any data except top holders. 

Example: http://open-explorer.io/#/assets/1.3.2767

Many other new assets are having this problem. More specifically, `get_asset_and_volume` api call failing, returning 500 to browsers.

**Comment by oxarbitrage** [comment]
thanks @HarukaMa . this is because `get_asset_and_volume` uses the postgres database to get some of its data. this data is populated once a day so the call was failing as no data was present for the asset yet. i now added a try block in order to get this data(from the database) only if available and return the rest(from the blolckchain) if it is not. 

now is working: http://open-explorer.io/#/assets/1.3.2767
